import {
    ADD_REPO_START,
    ADD_REPO_SUCCESS,
    ADD_REPO_FAILURE,
} from '../actions/repoActions';

const initialState = {
    repos: [
        {
            "id": 50264296,
            "node_id": "MDEwOlJlcG9zaXRvcnk1MDI2NDI5Ng==",
            "name": "bulma",
            "full_name": "jgthms/bulma",
            "private": false,
            "owner": {
                "login": "jgthms",
                "id": 1254808,
                "node_id": "MDQ6VXNlcjEyNTQ4MDg=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/1254808?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/jgthms",
                "html_url": "https://github.com/jgthms",
                "followers_url": "https://api.github.com/users/jgthms/followers",
                "following_url": "https://api.github.com/users/jgthms/following{/other_user}",
                "gists_url": "https://api.github.com/users/jgthms/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/jgthms/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/jgthms/subscriptions",
                "organizations_url": "https://api.github.com/users/jgthms/orgs",
                "repos_url": "https://api.github.com/users/jgthms/repos",
                "events_url": "https://api.github.com/users/jgthms/events{/privacy}",
                "received_events_url": "https://api.github.com/users/jgthms/received_events",
                "type": "User",
                "site_admin": false
            },
            "html_url": "https://github.com/jgthms/bulma",
            "description": "Modern CSS framework based on Flexbox",
            "fork": false,
            "url": "https://api.github.com/repos/jgthms/bulma",
            "forks_url": "https://api.github.com/repos/jgthms/bulma/forks",
            "keys_url": "https://api.github.com/repos/jgthms/bulma/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/jgthms/bulma/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/jgthms/bulma/teams",
            "hooks_url": "https://api.github.com/repos/jgthms/bulma/hooks",
            "issue_events_url": "https://api.github.com/repos/jgthms/bulma/issues/events{/number}",
            "events_url": "https://api.github.com/repos/jgthms/bulma/events",
            "assignees_url": "https://api.github.com/repos/jgthms/bulma/assignees{/user}",
            "branches_url": "https://api.github.com/repos/jgthms/bulma/branches{/branch}",
            "tags_url": "https://api.github.com/repos/jgthms/bulma/tags",
            "blobs_url": "https://api.github.com/repos/jgthms/bulma/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/jgthms/bulma/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/jgthms/bulma/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/jgthms/bulma/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/jgthms/bulma/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/jgthms/bulma/languages",
            "stargazers_url": "https://api.github.com/repos/jgthms/bulma/stargazers",
            "contributors_url": "https://api.github.com/repos/jgthms/bulma/contributors",
            "subscribers_url": "https://api.github.com/repos/jgthms/bulma/subscribers",
            "subscription_url": "https://api.github.com/repos/jgthms/bulma/subscription",
            "commits_url": "https://api.github.com/repos/jgthms/bulma/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/jgthms/bulma/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/jgthms/bulma/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/jgthms/bulma/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/jgthms/bulma/contents/{+path}",
            "compare_url": "https://api.github.com/repos/jgthms/bulma/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/jgthms/bulma/merges",
            "archive_url": "https://api.github.com/repos/jgthms/bulma/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/jgthms/bulma/downloads",
            "issues_url": "https://api.github.com/repos/jgthms/bulma/issues{/number}",
            "pulls_url": "https://api.github.com/repos/jgthms/bulma/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/jgthms/bulma/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/jgthms/bulma/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/jgthms/bulma/labels{/name}",
            "releases_url": "https://api.github.com/repos/jgthms/bulma/releases{/id}",
            "deployments_url": "https://api.github.com/repos/jgthms/bulma/deployments",
            "created_at": "2016-01-23T23:48:34Z",
            "updated_at": "2019-12-12T18:48:24Z",
            "pushed_at": "2019-12-11T23:23:35Z",
            "git_url": "git://github.com/jgthms/bulma.git",
            "ssh_url": "git@github.com:jgthms/bulma.git",
            "clone_url": "https://github.com/jgthms/bulma.git",
            "svn_url": "https://github.com/jgthms/bulma",
            "homepage": "https://bulma.io",
            "size": 82667,
            "stargazers_count": 37721,
            "watchers_count": 37721,
            "language": "CSS",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": true,
            "forks_count": 3125,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 297,
            "license": {
                "key": "mit",
                "name": "MIT License",
                "spdx_id": "MIT",
                "url": "https://api.github.com/licenses/mit",
                "node_id": "MDc6TGljZW5zZTEz"
            },
            "forks": 3125,
            "open_issues": 297,
            "watchers": 37721,
            "default_branch": "master",
            "temp_clone_token": null,
            "network_count": 3125,
            "subscribers_count": 683
        },
        {
            "id": 15480067,
            "node_id": "MDEwOlJlcG9zaXRvcnkxNTQ4MDA2Nw==",
            "name": "react-bootstrap",
            "full_name": "react-bootstrap/react-bootstrap",
            "private": false,
            "owner": {
                "login": "react-bootstrap",
                "id": 6853419,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjY4NTM0MTk=",
                "avatar_url": "https://avatars3.githubusercontent.com/u/6853419?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/react-bootstrap",
                "html_url": "https://github.com/react-bootstrap",
                "followers_url": "https://api.github.com/users/react-bootstrap/followers",
                "following_url": "https://api.github.com/users/react-bootstrap/following{/other_user}",
                "gists_url": "https://api.github.com/users/react-bootstrap/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/react-bootstrap/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/react-bootstrap/subscriptions",
                "organizations_url": "https://api.github.com/users/react-bootstrap/orgs",
                "repos_url": "https://api.github.com/users/react-bootstrap/repos",
                "events_url": "https://api.github.com/users/react-bootstrap/events{/privacy}",
                "received_events_url": "https://api.github.com/users/react-bootstrap/received_events",
                "type": "Organization",
                "site_admin": false
            },
            "html_url": "https://github.com/react-bootstrap/react-bootstrap",
            "description": "Bootstrap components built with React",
            "fork": false,
            "url": "https://api.github.com/repos/react-bootstrap/react-bootstrap",
            "forks_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/forks",
            "keys_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/teams",
            "hooks_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/hooks",
            "issue_events_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/issues/events{/number}",
            "events_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/events",
            "assignees_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/assignees{/user}",
            "branches_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/branches{/branch}",
            "tags_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/tags",
            "blobs_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/languages",
            "stargazers_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/stargazers",
            "contributors_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/contributors",
            "subscribers_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/subscribers",
            "subscription_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/subscription",
            "commits_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/contents/{+path}",
            "compare_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/merges",
            "archive_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/downloads",
            "issues_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/issues{/number}",
            "pulls_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/labels{/name}",
            "releases_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/releases{/id}",
            "deployments_url": "https://api.github.com/repos/react-bootstrap/react-bootstrap/deployments",
            "created_at": "2013-12-27T19:06:07Z",
            "updated_at": "2019-12-12T19:25:16Z",
            "pushed_at": "2019-12-12T18:41:06Z",
            "git_url": "git://github.com/react-bootstrap/react-bootstrap.git",
            "ssh_url": "git@github.com:react-bootstrap/react-bootstrap.git",
            "clone_url": "https://github.com/react-bootstrap/react-bootstrap.git",
            "svn_url": "https://github.com/react-bootstrap/react-bootstrap",
            "homepage": "https://react-bootstrap.github.io/",
            "size": 17973,
            "stargazers_count": 16756,
            "watchers_count": 16756,
            "language": "JavaScript",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "forks_count": 2724,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 113,
            "license": {
                "key": "mit",
                "name": "MIT License",
                "spdx_id": "MIT",
                "url": "https://api.github.com/licenses/mit",
                "node_id": "MDc6TGljZW5zZTEz"
            },
            "forks": 2724,
            "open_issues": 113,
            "watchers": 16756,
            "default_branch": "master",
            "temp_clone_token": null,
            "organization": {
                "login": "react-bootstrap",
                "id": 6853419,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjY4NTM0MTk=",
                "avatar_url": "https://avatars3.githubusercontent.com/u/6853419?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/react-bootstrap",
                "html_url": "https://github.com/react-bootstrap",
                "followers_url": "https://api.github.com/users/react-bootstrap/followers",
                "following_url": "https://api.github.com/users/react-bootstrap/following{/other_user}",
                "gists_url": "https://api.github.com/users/react-bootstrap/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/react-bootstrap/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/react-bootstrap/subscriptions",
                "organizations_url": "https://api.github.com/users/react-bootstrap/orgs",
                "repos_url": "https://api.github.com/users/react-bootstrap/repos",
                "events_url": "https://api.github.com/users/react-bootstrap/events{/privacy}",
                "received_events_url": "https://api.github.com/users/react-bootstrap/received_events",
                "type": "Organization",
                "site_admin": false
            },
            "network_count": 2724,
            "subscribers_count": 465
        },
        {
            "id": 65794292,
            "node_id": "MDEwOlJlcG9zaXRvcnk2NTc5NDI5Mg==",
            "name": "styled-components",
            "full_name": "styled-components/styled-components",
            "private": false,
            "owner": {
                "login": "styled-components",
                "id": 20658825,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjIwNjU4ODI1",
                "avatar_url": "https://avatars2.githubusercontent.com/u/20658825?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/styled-components",
                "html_url": "https://github.com/styled-components",
                "followers_url": "https://api.github.com/users/styled-components/followers",
                "following_url": "https://api.github.com/users/styled-components/following{/other_user}",
                "gists_url": "https://api.github.com/users/styled-components/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/styled-components/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/styled-components/subscriptions",
                "organizations_url": "https://api.github.com/users/styled-components/orgs",
                "repos_url": "https://api.github.com/users/styled-components/repos",
                "events_url": "https://api.github.com/users/styled-components/events{/privacy}",
                "received_events_url": "https://api.github.com/users/styled-components/received_events",
                "type": "Organization",
                "site_admin": false
            },
            "html_url": "https://github.com/styled-components/styled-components",
            "description": "Visual primitives for the component age. Use the best bits of ES6 and CSS to style your apps without stress 💅",
            "fork": false,
            "url": "https://api.github.com/repos/styled-components/styled-components",
            "forks_url": "https://api.github.com/repos/styled-components/styled-components/forks",
            "keys_url": "https://api.github.com/repos/styled-components/styled-components/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/styled-components/styled-components/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/styled-components/styled-components/teams",
            "hooks_url": "https://api.github.com/repos/styled-components/styled-components/hooks",
            "issue_events_url": "https://api.github.com/repos/styled-components/styled-components/issues/events{/number}",
            "events_url": "https://api.github.com/repos/styled-components/styled-components/events",
            "assignees_url": "https://api.github.com/repos/styled-components/styled-components/assignees{/user}",
            "branches_url": "https://api.github.com/repos/styled-components/styled-components/branches{/branch}",
            "tags_url": "https://api.github.com/repos/styled-components/styled-components/tags",
            "blobs_url": "https://api.github.com/repos/styled-components/styled-components/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/styled-components/styled-components/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/styled-components/styled-components/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/styled-components/styled-components/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/styled-components/styled-components/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/styled-components/styled-components/languages",
            "stargazers_url": "https://api.github.com/repos/styled-components/styled-components/stargazers",
            "contributors_url": "https://api.github.com/repos/styled-components/styled-components/contributors",
            "subscribers_url": "https://api.github.com/repos/styled-components/styled-components/subscribers",
            "subscription_url": "https://api.github.com/repos/styled-components/styled-components/subscription",
            "commits_url": "https://api.github.com/repos/styled-components/styled-components/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/styled-components/styled-components/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/styled-components/styled-components/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/styled-components/styled-components/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/styled-components/styled-components/contents/{+path}",
            "compare_url": "https://api.github.com/repos/styled-components/styled-components/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/styled-components/styled-components/merges",
            "archive_url": "https://api.github.com/repos/styled-components/styled-components/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/styled-components/styled-components/downloads",
            "issues_url": "https://api.github.com/repos/styled-components/styled-components/issues{/number}",
            "pulls_url": "https://api.github.com/repos/styled-components/styled-components/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/styled-components/styled-components/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/styled-components/styled-components/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/styled-components/styled-components/labels{/name}",
            "releases_url": "https://api.github.com/repos/styled-components/styled-components/releases{/id}",
            "deployments_url": "https://api.github.com/repos/styled-components/styled-components/deployments",
            "created_at": "2016-08-16T06:41:32Z",
            "updated_at": "2019-12-12T21:26:13Z",
            "pushed_at": "2019-12-02T09:34:47Z",
            "git_url": "git://github.com/styled-components/styled-components.git",
            "ssh_url": "git@github.com:styled-components/styled-components.git",
            "clone_url": "https://github.com/styled-components/styled-components.git",
            "svn_url": "https://github.com/styled-components/styled-components",
            "homepage": "https://styled-components.com",
            "size": 9112,
            "stargazers_count": 27042,
            "watchers_count": 27042,
            "language": "JavaScript",
            "has_issues": true,
            "has_projects": false,
            "has_downloads": true,
            "has_wiki": false,
            "has_pages": false,
            "forks_count": 1622,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 129,
            "license": {
                "key": "mit",
                "name": "MIT License",
                "spdx_id": "MIT",
                "url": "https://api.github.com/licenses/mit",
                "node_id": "MDc6TGljZW5zZTEz"
            },
            "forks": 1622,
            "open_issues": 129,
            "watchers": 27042,
            "default_branch": "master",
            "temp_clone_token": null,
            "organization": {
                "login": "styled-components",
                "id": 20658825,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjIwNjU4ODI1",
                "avatar_url": "https://avatars2.githubusercontent.com/u/20658825?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/styled-components",
                "html_url": "https://github.com/styled-components",
                "followers_url": "https://api.github.com/users/styled-components/followers",
                "following_url": "https://api.github.com/users/styled-components/following{/other_user}",
                "gists_url": "https://api.github.com/users/styled-components/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/styled-components/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/styled-components/subscriptions",
                "organizations_url": "https://api.github.com/users/styled-components/orgs",
                "repos_url": "https://api.github.com/users/styled-components/repos",
                "events_url": "https://api.github.com/users/styled-components/events{/privacy}",
                "received_events_url": "https://api.github.com/users/styled-components/received_events",
                "type": "Organization",
                "site_admin": false
            },
            "network_count": 1622,
            "subscribers_count": 385
        }

    ],
    isFetching: false,
    error: ''
}

const repoReducer = (state = initialState, action) => {
    console.log(action.payload)
    console.log(state, action)
    switch (action.type) {
        case ADD_REPO_START:
            return {
                ...state,
                isFetching: true
            }
        case ADD_REPO_SUCCESS:
            return {
                ...state,
                isFetching: false,
                error: '',
                repos: [
                    ...state.repos,
                    action.payload
                ]
            }
        case ADD_REPO_FAILURE:
            return {
                ...state,
                isFetching: false,
                error: action.payload
            };
        default:
            return state;
    }
}

export default repoReducer;